version: '3.9'

services:
  postgres: 
    image: postgres:17.4-alpine3.20
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mosmetro_db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mosmetro"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      network: 
        ipv4_address: 10.7.0.2
    env_file: ".env"

  server:
    build: ./
    ports:
      - 8080:8080
    networks:
      network: 
        ipv4_address: 10.7.0.3
    env_file: ".env"
    depends_on:
      - postgres

volumes:
  mosmetro_db-data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1
